modLoader="javafml"
loaderVersion="[36,)"

license="MIT"
issueTrackerURL="https://github.com/Hellish-Mods/BlackMirrorJS/issues"

[[mods]]
modId="blackmirrorjs"
version="${file.jarVersion}"

displayName="BlackMirrorJS"
displayURL="https://www.curseforge.com/minecraft/mc-mods/blackmirrorjs"
logoFile="pack.png"

authors="Hellish Mods & Modern Modpacks"
credits="""
G_cat (Coding)
"""

description="Allows script devs to reflect potentially dangerous classes using a permission-based system"

[[dependencies.blackmirrorjs]]
    modId="forge"
    mandatory=true

    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blackmirrorjs]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blackmirrorjs]]
    modId="kubejs"
    mandatory=true

    versionRange=","
    ordering="NONE"
    side="BOTH"